// Exact 5-fold differential cross section for e+e- pair production in
// ultraperipheral heavy-ion collisions, ported from ../TEPEMGEN/diffcross.f.
//
//   A. Alscher, K. Hencken, D. Trautmann, G. Baur, Phys. Rev. A55 (1997) 396
//   Copyright (c) 1997, 1998, 2002 Adrian Alscher and Kai Hencken
//   See ../TEPEMGEN/diffcross.f for the full copyright notice.
//
// Templated on the arithmetic type so the same source can be evaluated in
// double, in __float128, or in a user-supplied type (Boost.Multiprecision, or
// an interval type for a round-off analysis). That is not generality for its
// own sake: at LHC energies the double result loses most of its significant
// digits, which is what O2-6340 is about. diffcross.f said so in 1997 --
// "double precision variables should better be real*16", line 27 -- and the
// advice was never followed.
//
// Everything except the scaffolding here is generated by tools/gen_diffcross.py
// into DiffCrossGenerated.inc; see that script for why.
#ifndef TEPEMGENCPP_DIFFCROSS_H
#define TEPEMGENCPP_DIFFCROSS_H

#include <cmath>

#ifdef __SIZEOF_FLOAT128__
#include <quadmath.h>
#endif

namespace o2::aegis::tepemgen
{

// ---------------------------------------------------------------------------
// Arithmetic scaffolding
// ---------------------------------------------------------------------------

// Bring the standard overloads into this namespace so that the UNQUALIFIED
// calls in the generated code resolve for double, and so that adding the
// __float128 overloads below does not hide them. Unqualified lookup stops at
// the first enclosing scope that declares the name, so if this namespace
// declared only the __float128 sqrt, `sqrt(double)` would fail to compile.
//
// The generated code must never contain a qualified std::sqrt: on a Boost
// multiprecision type that silently converts to double and throws away exactly
// the precision this port exists to provide. ADL brings in the right overloads
// for such types automatically.
using std::abs;
using std::acos;
using std::cos;
using std::cosh;
using std::log;
using std::sin;
using std::sinh;
using std::sqrt;

#ifdef __SIZEOF_FLOAT128__
// __float128 is a builtin, not a class type, so ADL finds nothing for it and
// these must be visible by ordinary lookup from the generated code.
inline __float128 sqrt(__float128 x) { return ::sqrtq(x); }
inline __float128 log(__float128 x) { return ::logq(x); }
inline __float128 cosh(__float128 x) { return ::coshq(x); }
inline __float128 sinh(__float128 x) { return ::sinhq(x); }
inline __float128 cos(__float128 x) { return ::cosq(x); }
inline __float128 sin(__float128 x) { return ::sinq(x); }
inline __float128 abs(__float128 x) { return ::fabsq(x); }
inline __float128 acos(__float128 x) { return ::acosq(x); }
#endif

/// x^N by squaring, evaluating x once.
/// Replaces Fortran's `**`. Not std::pow: that is slow, and on a user-supplied
/// type it either fails to compile or silently narrows to double.
template <int N, typename T>
constexpr T ipow(T x)
{
  static_assert(N >= 0, "negative exponents do not occur in diffcross.f");
  if constexpr (N == 0) {
    return T(1);
  } else if constexpr (N == 1) {
    return x;
  } else if constexpr (N % 2 == 0) {
    const T h = ipow<N / 2>(x);
    return h * h;
  } else {
    return x * ipow<N - 1>(x);
  }
}

/// pi at the full precision of T.
///
/// A literal cannot do this: `T(3.14159...)` builds a *double* first and only
/// then widens, so everything past the 17th digit is gone before T sees it --
/// silently, and precisely in the quad build. `acos(-1)` instead, which is
/// evaluated at T's own precision whatever T is. (M_PIq would also work for
/// __float128, but its `Q` suffix needs -fext-numeric-literals, and requiring
/// a GCC-specific flag of every consumer of a header is a poor trade for a
/// constant computed once.)
template <typename T>
struct PiConst {
#ifdef TEPEMGEN_FORTRAN_PI
  /// Diagnostic build: the 25-digit literal from diffcross.f, reproduced
  /// exactly. Its purpose is to show that the residual disagreement between
  /// this port and the REAL*16 Fortran is that truncated constant amplified by
  /// ill-conditioning, and not a transcription error. True pi continues
  /// ...38327950288, so the Fortran constant is only good to ~1e-25 -- fine in
  /// double, visible in quad. Not for production: acos(-1) is more accurate.
  ///
  /// Built as exact rationals because the numerator 3141592653589793238462643
  /// overflows every integer type, and a decimal literal would round to double.
  static T value()
  {
    return T(3141592653589793) / T(1000000000000000) +
           T(238462643) / T(1000000000) / T(1000000000000000);
  }
#else
  static T value() { return acos(T(-1)); }
#endif
};

template <typename T>
inline const T pi = PiConst<T>::value();

/// A transverse 2-vector. Replaces the `DOUBLE PRECISION x(2)` arrays.
template <typename T>
struct Vec2 {
  T x, y;
};

/// COMMON /PHYSPARAM/, made explicit.
///
/// In the Fortran this is global mutable state shared by the whole call tree,
/// which is why two generator instances in one process would silently corrupt
/// each other. Passing it makes the code reentrant and thread-safe.
template <typename T>
struct PhysParams {
  T gamma, beta, m, w1xw1, w1xw2, w2xw2, wl, wy;
};

/// Set up the beam-dependent parameters. `energy` is per nucleon pair in GeV,
/// `mass` the produced lepton mass in MeV. Ported from SUBROUTINE Initdiffcross.
template <typename T>
PhysParams<T> initDiffCross(T energy, T mass)
{
  PhysParams<T> p{};
  // "Approximation energy per nucleon divided by proton mass" -- as in the
  // Fortran; 0.938 GeV is the proton mass.
  //
  // T(938)/T(1000), not T(0.938): the latter parses 0.938 as a double and
  // rounds it before T sees it, while gfortran parses 0.938D0 at the full
  // width of T. Since 0.938 is not dyadic that costs ~1e-17 relative, which
  // is invisible in double and dominates the quad comparison.
  p.gamma = energy / (T(2) * (T(938) / T(1000)));
  // beta = sqrt(1 - 1/gamma^2), written factored. That form is deliberate and
  // worth keeping: it avoids cancelling 1 against 1/gamma^2, which at
  // gamma ~ 2860 differ by fourteen orders of magnitude.
  p.beta = sqrt((T(1) - T(1) / p.gamma) * (T(1) + T(1) / p.gamma));
  p.m = mass;
  p.w1xw1 = T(1) / ipow<2>(p.gamma);
  p.w2xw2 = T(1) / ipow<2>(p.gamma);
  p.w1xw2 = T(2) - T(1) / ipow<2>(p.gamma);
  p.wl = sqrt(p.w1xw1);
  // ARCOSH, a Fortran statement function in the original.
  p.wy = log(p.gamma + sqrt((p.gamma - T(1)) * (p.gamma + T(1))));
  return p;
}

// ---------------------------------------------------------------------------
// Iz0 -- hand-written, because it is the one integral function with a branch
// ---------------------------------------------------------------------------

/// The Fortran guards `arg < 0`, which can only happen for u*v < 0, and on that
/// branch sets a COMMON flag that is inspected much later. Two changes here:
///
///  * the flag is an out-parameter rather than global state, and
///  * `arg` is reused rather than recomputed. The original evaluates the same
///    expression twice, once to test and once to take the log, so the test and
///    the value could drift apart under editing.
///
/// Note what is *not* guarded, in the original or here: `arg -> 0` (log of
/// zero) and `s -> 0` (division by zero). `s` is real whenever u,v > 0 --
/// (tepxx+u+v)^2 >= (u+v)^2 >= 4uv by AM-GM, since tepxx >= 0 -- so the square
/// root itself is safe; it is the vanishing that is not handled.
template <typename T>
T Iz0(const Vec2<T>& x, T u, T v, bool& ok)
{
  const T tepxx = x.x * x.x + x.y * x.y;
  const T s = sqrt(ipow<2>(tepxx + u + v) - 4 * u * v);
  const T arg = ipow<2>(tepxx + u + v + s) / (4 * u * v);
  if (arg < T(0)) {
    ok = false;
    return T(0);
  }
  return pi<T> * log(arg) / s;
}

#include "DiffCrossGenerated.inc"

// ---------------------------------------------------------------------------
// The public entry point
// ---------------------------------------------------------------------------

template <typename T>
struct DiffCrossResult {
  T dsigma;    ///< kbarn/MeV^4/(Z*alpha)^4, as the Fortran returns
  bool ok;     ///< false if an unphysical branch was taken (Fortran: setzero)
  T survival;  ///< |NT| / max|Ni| at the moment of summation -- see below
};

/// Evaluate the differential cross section at one kinematic point.
///
/// Deliberately does NOT reproduce the Fortran's final guard
///
///     IF((setzero.EQ.1).OR.(dsigma.LT.0)) THEN dsigma=0; badcount=badcount+1
///
/// That test is unsound and replacing it is a large part of the point of this
/// port. Cancellation produces garbage of either sign, so testing the sign
/// catches only half of it: measured over 100k sampled points it fires on
/// 0.019% while 0.25% are more than 10% wrong -- about one bad point in
/// thirteen. Worse, the half it misses is the positive half, which flows on
/// into the weight and the variance estimate.
///
/// `survival` is reported instead. It is |NT| / max|Ni|: the fraction of the
/// summed amplitude that was not destroyed by cancellation, taken before the
/// normalisation factors are applied. Near the machine epsilon of T the result
/// carries no significant digits, and the caller should re-evaluate the point
/// in a wider type rather than discard it. See doc/02-findings.md section 3.
template <typename T>
DiffCrossResult<T> diffCross(const PhysParams<T>& phys, T ppvt, T yp, T pmvt,
                             T ym, T dphi)
{
  bool ok = true;
  T survival{};
  const T nt = diffCrossTerms(phys, ppvt, yp, pmvt, ym, dphi, ok, &survival);
  return {nt, ok, survival};
}

}  // namespace o2::aegis::tepemgen

#endif  // TEPEMGENCPP_DIFFCROSS_H
